FROM python:3.9-rc-alpine

LABEL maintainer="Jhonnatan Dias Costa"

ARG ACCESS_KEY
ARG SECRET_KEY
ARG AWS_BUCKET

ENV HOME /admin

ENV ACCESS_KEY $ACCESS_KEY
ENV SECRET_KEY $SECRET_KEY
ENV AWS_BUCKET $AWS_BUCKET

RUN pip3 install boto3 --quiet

RUN mkdir --parents $HOME

WORKDIR $HOME

COPY script.py ./

ENTRYPOINT [ "python3", "script.py" ]
