Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName    

Resources:
  SGBase:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acesso via SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-06b263d6ceff0b3dd
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups: [ !Ref SGBase ]

        