Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: bucket-s3-desafio

  RootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /

  RolePolicies:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "bucket-access"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - Effect: "Allow"
            Action:
              - s3:ListBucket
              - s3:GetObject
              - s3:PutObject
            Resource: !GetAtt S3Bucket.Arn
      Roles:
        - !Ref RootRole

  EC2InstanceProfile: 
    Type: AWS::IAM::InstanceProfile
    Properties: 
      Path: "/"
      Roles: 
        - !Ref RootRole

  SGBase:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Permitir acesso via SSH
      SecurityGroupIngress:
        - IpProtocol: tcp
          CidrIp: 0.0.0.0/0
          FromPort: 22
          ToPort: 22

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-06b263d6ceff0b3dd
      InstanceType: t2.micro
      KeyName: !Ref KeyName
      SecurityGroups: [ !Ref SGBase ]
      IamInstanceProfile: !Ref EC2InstanceProfile

        